### ISSUE TITLE
Can't be used to send Backlog

### ISSUE THREAD

**Issue by rschitz** [akiifall/homebridge-mqtt-toggleswitch#1]
I need to be able to send Backlog or RfRaw command but it seems to filter the "onValue" so i cant send large sequence like the rf raw ones.

https://tasmota.github.io/docs/devices/Sonoff-RF-Bridge-433/#learning-commands-with-portisch-firmware

basically i need to be able to do this:
`mosquitto_pub -t "cmnd/tasmota_C36BA6/Backlog" -m "RfRaw AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955; RfRaw 0"`
or at least this:
`mosquitto_pub -t "cmnd/tasmota_C36BA6/RfRaw" -m "AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955"`

**Comment by akiifall** [comment]
> I need to be able to send Backlog or RfRaw command but it seems to filter the "onValue" so i cant send large sequence like the rf raw ones.
> 
> https://tasmota.github.io/docs/devices/Sonoff-RF-Bridge-433/#learning-commands-with-portisch-firmware
> 
> basically i need to be able to do this: `mosquitto_pub -t "cmnd/tasmota_C36BA6/Backlog" -m "RfRaw AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955; RfRaw 0"` or at least this: `mosquitto_pub -t "cmnd/tasmota_C36BA6/RfRaw" -m "AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955"`

onValue is return value after sending onCommand

if you send some command or raw , you can use like this

"onCommand": "{\"Command\":\"AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955\"}",

**Comment by rschitz** [comment]
Hi and thanks for your feedback.
how could i send the "RfRaw AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955; RfRaw 0"? should i escape the spaces or something?

**Comment by akiifall** [comment]
> Hi and thanks for your feedback.
> how could i send the "RfRaw AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955; RfRaw 0"? should i escape the spaces or something?


"onCommand": "RfRaw AAB02304081964060402BC7BF238100A291000000A291A292929100A29291A292929100A292955; RfRaw 0",

edit config like this. works good. ^^

**Comment by rschitz** [comment]
works like a charm, thanks a lot for your help.
sorry for the late feedback
